version: '3'
services:
  nn01:
    image: hd-hive-spark
    container_name: nn01
    hostname: nn01
    # ports:
    #   - 50090:50090
    #   - 50070:50070
    volumes:
      - ./conf:/hdetc
    env_file:
      - hd.env
    depends_on:
      - hive-mysql
      - dn01
      - dn02
      - dn03
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.1

  dn01:
    image: hanode
    container_name: dn01
    hostname: dn01
    # ports:
    #   - 8042:8042
    volumes:
      - ./conf:/hdetc
    env_file:
      - hd.env
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.101

  dn02:
    image: hanode
    container_name: dn02
    hostname: dn02
    # ports:
    #   - 8042:8042
    volumes:
      - ./conf:/hdetc
    env_file:
      - hd.env
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.102

  dn03:
    image: hanode
    container_name: dn03
    hostname: dn03
    # ports:
    #   - 8042:8042
    volumes:
      - ./conf:/hdetc
    env_file:
      - hd.env
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.103

  rm01:
    image: hanode
    container_name: rm01
    hostname: rm01
    # ports:
    #   - 8088:8088
    #   - 19888:19888
    volumes:
      - ./conf:/hdetc
    env_file:
      - hd.env
    depends_on:
      - dn01
      - dn02
      - dn03
      - nn01
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.20

  hive-mysql:
    image: mysql
    hostname: dn01
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.201
  
  nginx:
    image: hdnginx
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
    networks:
      hdxnet: 
        ipv4_address: 172.23.101.210
    
networks:
  hdxnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
        # - gateway: 172.23.0.1
