version: '3'
services:
  zk01:
    image: env-zknode
    container_name: zk01
    hostname: zk01
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVER_1: zk01:2888:3888
      ZOO_SERVER_2: zk02:2888:3888
      ZOO_SERVER_3: zk03:2888:3888
    networks:
      datanet: 
        ipv4_address: 172.24.101.1
  zk02:
    image: env-zknode
    container_name: zk02
    hostname: zk02
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVER_1: zk01:2888:3888
      ZOO_SERVER_2: zk02:2888:3888
      ZOO_SERVER_3: zk03:2888:3888
    ports:
      - "2182:2181"
    networks:
      datanet: 
        ipv4_address: 172.24.101.2
  zk03:
    image: env-zknode
    container_name: zk03
    hostname: zk03
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVER_1: zk01:2888:3888
      ZOO_SERVER_2: zk02:2888:3888
      ZOO_SERVER_3: zk03:2888:3888
    networks:
      datanet: 
        ipv4_address: 172.24.101.3

networks:
  datanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
        # - gateway: 172.24.0.1
