version: '3'
services:
  zk01:
    image: env-zknode
    container_name: zk01
    hostname: zk01
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVER_1: zk01:2888:3888
      ZOO_SERVER_2: zk02:2888:3888
      ZOO_SERVER_3: zk03:2888:3888
    networks:
      datanet: 
        ipv4_address: 172.24.102.1
  zk02:
    image: env-zknode
    container_name: zk02
    hostname: zk02
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVER_1: zk01:2888:3888
      ZOO_SERVER_2: zk02:2888:3888
      ZOO_SERVER_3: zk03:2888:3888
    networks:
      datanet: 
        ipv4_address: 172.24.102.2
  zk03:
    image: env-zknode
    container_name: zk03
    hostname: zk03
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVER_1: zk01:2888:3888
      ZOO_SERVER_2: zk02:2888:3888
      ZOO_SERVER_3: zk03:2888:3888
    networks:
      datanet: 
        ipv4_address: 172.24.102.3
  kemysql:
    image: mysql:5.7
    container_name: kemysql
    hostname: kemysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      datanet: 
        ipv4_address: 172.24.102.200
  ka01:
    image: kafka-eagle-webui
    container_name: ka01
    hostname: ka01
    depends_on:
      - zk01
      - zk02
      - zk03
      - ka02
      - ka03
      - kemysql
    ports:
      - "8048:8048"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LISTENERS: "PLAINTEXT://ka01:9092"
      KAFKA_LOG_DIRS: "/opt/module/kafka/data"
      KAFKA_ZOOKEEPER_CONNECT: "zk01:2181,zk02:2181,zk03:2181"
      KE_KAFKA_EAGLE_ZK_CLUSTER_ALIAS: cluster1
      KE_CLUSTER1_ZK_LIST: "zk01:2181,zk02:2181,zk03:2181"
      KE_CLUSTER1_KAFKA_EAGLE_OFFSET_STORAGE: kafka
      KE_KAFKA_EAGLE_METRICS_CHARTS: "true"
      # KE_KAFKA_EAGLE_DRIVER: com.mysql.cj.jdbc.Driver
      KE_KAFKA_EAGLE_DRIVER: com.mysql.jdbc.Driver
      KE_KAFKA_EAGLE_URL: "jdbc:mysql://kemysql:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
      KE_KAFKA_EAGLE_USERNAME: root
      KE_KAFKA_EAGLE_PASSWORD: 1234
    networks:
      datanet: 
        ipv4_address: 172.24.102.4
  ka02:
    image: kafka-eagle-node
    container_name: ka02
    hostname: ka02
    depends_on:
      - zk01
      - zk02
      - zk03
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LISTENERS: "PLAINTEXT://ka02:9093"
      KAFKA_LOG_DIRS: "/opt/module/kafka/data"
      KAFKA_ZOOKEEPER_CONNECT: "zk01:2181,zk02:2181,zk03:2181"
    networks:
      datanet: 
        ipv4_address: 172.24.102.5
  ka03:
    image: kafka-eagle-node
    container_name: ka03
    hostname: ka03
    depends_on:
      - zk01
      - zk02
      - zk03
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LISTENERS: "PLAINTEXT://ka03:9094"
      KAFKA_LOG_DIRS: "/opt/module/kafka/data"
      KAFKA_ZOOKEEPER_CONNECT: "zk01:2181,zk02:2181,zk03:2181"
    networks:
      datanet: 
        ipv4_address: 172.24.102.6

networks:
  datanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
        # - gateway: 172.24.0.1
